//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniChan8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        public int anim_id { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public string description_ { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> ep { get; set; }
        public string thumbnail { get; set; }
        public string trailer { get; set; }
        public Nullable<bool> warning { get; set; }
        public Nullable<bool> premium { get; set; }
        public Nullable<bool> movie { get; set; }
        public string poster { get; set; }
        public string slide { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
    }
}
